baseURL = "https://vikaas.netlify.app/"
languageCode = "en-us"
title = "Vikas Rajpoot"
theme = "PaperMod"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "work"
    name = "Work"
    url = "work"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3


[params]
   mainSections = ["posts"]
  ShowBreadCrumbs = true
  ShowReadingTime = false
  ShowShareButtons = false
  defaultTheme = "light"  # You can set "dark" or "light"
  disableThemeToggle = true  # This removes the theme changer

  [params.homeInfoParams]
  enabled = true
  title = "Hello there"
  subtitle = "I am Vikas Rajpoot, a Web Developer & Programmer. I write about programming, productivity, and technology."

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/vikasrajpoot30"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/vikas-rajpoot"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/vikasrajpoot_30"
