baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My o Blog"
theme = "PaperMod"

[menu]
  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

  [[menu.main]]
  name = "Work"
  url = "/work/"
  weight = 2

  [[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 3

[params]
  ShowBreadCrumbs = false
  ShowReadingTime = false
  ShowShareButtons = false

  [params.profileMode]
  enabled = true
  title = "Hello there"
  subtitle = "I am Vikas Rajpoot, a Web Developer & Programmer. I write about programming, productivity, and technology."

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/yourusername"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/yourusername"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/yourusername"
